apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-smtp
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    vault.security.banzaicloud.io/vault-addr: "https://vault.internal.iclinic.tools"
    vault.security.banzaicloud.io/vault-role: "core-shared-main-cluster-vault-secrets-webhook"
    vault.security.banzaicloud.io/vault-path: "kubernetes-core-shared-main"
    vault.security.banzaicloud.io/inline-mutation: "true"
stringData:
  SENTRY_EMAIL_PASSWORD: ${vault:secret/data/kubernetes/core/shared/main/sentry#mail_password}
  SENTRY_EMAIL_HOST:     ${vault:secret/data/kubernetes/core/shared/main/sentry#mail_host}